import Head from "next/head";
import Image from "next/image";
import ToDo from "../components/CreateToDo";
import styles from "../styles/Home.module.css";
import ToDoTailwind from "./tailw";

export default function Home() {
  return (
    <div className="flex bg-gray-300 w-screen min-h-screen items-center justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex space-x-6 ">
        <a className="bg-green-600 rounded-md px-5 py-3 " href="/tailw">
          Open With TailwindCSS and react hooks
        </a>
        <a className="bg-green-600 rounded-md px-5 py-3 " href="/mobx">
          Open With TailwindCSS and mobx
        </a>
      </main>
    </div>
  );
}
