import Head from "next/head";
import Image from "next/image";
import ToDo from "../components/CreateToDo";
import styles from "../styles/Home.module.css";
import ToDoTailwind from "./tailw";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ToDo />
        {/* <ToDoTailwind /> */}
        <a className="bg-green-600 rounded-sm px-5 py-3 " href="/tailw">
          Open With Tailwind and react hooks
        </a>
      </main>
    </div>
  );
}
